### ISSUE TITLE
Add switch to toggle reference image

### ISSUE THREAD

**Issue by guiszk** [lemmoor/jigsaw-svelte#10]
All current modes show the dimmed image behind the pieces, there could be an option to remove it, making the puzzle harder.

**Comment by lemmoor** [comment]
Good idea, I'll assign it to you.
Leave some kind of light square or any other indication though to show where the puzzles should be when the image is removed

**Comment by guiszk** [comment]
Do you want the toggle to be usable while the game is running, or should it only be enabled before the game starts?

**Comment by lemmoor** [comment]
Sorry for the late reply but yes, it should be usable while the game is running
