### ISSUE TITLE
Dockerize Svelte app

### ISSUE THREAD

**Issue by naXa777** [lemmoor/jigsaw-svelte#14]
Let's add Dockerfile, .dockerignore, and docker-compose.yml to your project.
More information in the article -> https://medium.com/@alpercitak/dockerize-sveltekit-1323771a12b1
I'm going to follow it step by step. Please assign me to this task.

Read here to learn more about what is Docker and why it's used https://www.docker.com/why-docker/

**Comment by lemmoor** [comment]
Thanks for the suggestion but I think it would only complicate things and I don't see any major benefits of adding Docker to this project
