### ISSUE TITLE
Add github link

### ISSUE THREAD

**Issue by lemmoor** [lemmoor/jigsaw-svelte#15]
Add a link to this github repo somewhere on the page.
You can make a navbar and put it there or just add a github icon somewhere on the side.

**Comment by thinhb1901951** [comment]
Hi, I love your game and I feel happy to join with it. Here is my code with navbar and GitHub link to you project:
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
  <title>Jigsaw puzzles</title>
</head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container">
    <div class="container-fluid">
      <ul class="navbar-nav">        
          <a href="https://github.com/lemmoor/jigsaw-svelte">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-github"
              viewBox="0 0 16 16">
              <path
                d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
            </svg>
            <p><b>GitHub</b></p>
          </a>
        </div>
      </ul>
    </div>
  </nav>


  <div id="app"></div>
  <script type="module" src="/src/main.js"></script>
</body>

</html>`

**Comment by thinhb1901951** [comment]
Hi, I love your game and I feel happy to join with it. How can I submit the code change??
