### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by lemmoor** [lemmoor/jigsaw-svelte#2]
Improve overall look of the website, you can remove picocss link from [index.html](https://github.com/lemmoor/jigsaw-svelte/blob/main/index.html) if you want.

**Comment by gaurav-iitb** [comment]
can you please assign this to me

**Comment by lemmoor** [comment]
Sure!

**Comment by lemmoor** [comment]
@gaurav-iitb hey, it's been 2 weeks, are you working on it or should i assing someone else?

**Comment by Cimlah** [comment]
Hey,
Please assign this issue to me.
