### ISSUE TITLE
Add difficulty modes 

### ISSUE THREAD

**Issue by lemmoor** [lemmoor/jigsaw-svelte#5]
Before start, add dificulty modes (easy, medium, hard) which change the amount of puzzle pieces. The default one shoud be easy.

**Comment by leec94** [comment]
hello! I'd like to take this issue for hacktobertest

**Comment by lemmoor** [comment]
@leec94 Sure! I assigned it to you

**Comment by leec94** [comment]
Thanks! I opened a pull request - let me know if it works for you.
