### ISSUE TITLE
Add a reset button

### ISSUE THREAD

**Issue by Krishnansh5** [lemmoor/jigsaw-svelte#7]
-  Add a reset button that resets all the pecies in some random place
- Also one thing I noticed that once the puzzle is solved, peices remain in that state on generation of a new puzzle. So reset should be called everytime on generation of new puzzle

**Comment by lemmoor** [comment]
Sure, but I think it shouldn't reset the pieces that are already in the right place. Unless it's on generation of a new puzzle of course.
Do you want to work on this issue?
